pipeline:
  # init:
  #   image: node:9.3.0
  #   commands:
  #     - npm i

  # build:
  #   image: node:9.3.0
  #   commands:
  #     - rm -rf build
  #     - npm run build

  publish:
    image: node:9.3.0
    secrets: [ npm_username, npm_password, npm_email ]
    commands:
      - node publish.js ${NPM_USERNAME} ${NPM_PASSWORD} ${NPM_EMAIL}
      - env
    when:
      branch: [master]