version: "3.4"

services:

  tool:
    build: .
    restart: always
    ports:
      - 5002:5001 # ssh
    volumes:
      - ./configs/config.json:/dist/config.json
    depends_on:
      - mysql
      - redis
      - elk
    command: /usr/sbin/sshd -p 5001 -D

  # worker:
  #   build: .
  #   restart: always
  #   ports:
  #     - 5002:5001 # ssh
  #   depends_on:
  #     - mysql
  #     - redis
  #     - elk
  #   command: node /dist/worker
  #   environment:
  #     NODE_NAME: "worker 1"

  seaport:
    image: makame/seaport
    ports:
      - 5000:80
    restart: always

  mysql:
    image: mysql
    restart: always
    ports:
      - 5003:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "qwerty"
      MYSQL_DATABASE: "karpov"

  redis:
    image: redis
    restart: always
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "qwerty"]
    volumes:
      - ./data/redis:/data

  elk:
    image: sebp/elk:latest
    restart: always
    ports:
      - 5001:5601 # Kubana
      - 5801:5801
      - 9200:9200 # Elastic
      # - 5044:5044 # Logstash
    volumes:
      - ./data/elasticsearch:/var/lib/elasticsearch
      - ./configs/logstash.conf:/etc/logstash/conf.d/winston.conf
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    # mem_limit: 1g

# volumes:
#   db-data: