query UsersList($filter: UserFilter!, $order: [UserOrder], $limit: Int, $offset: Int) {
    user {
        list(filter: $filter, order: $order, limit: $limit, offset: $offset) {
            users {
                id,
                username,
                avatar
            }
        }
    }
}