mutation Auth($login: String, $password: Password!) {
  auth {
    login(login: $login, password: $password) {
      sid,
      token,
      user {
        id,
        username,
        email,
        avatar,
        rules
      }
    }
  }
}